CREATE DATABASE LIBMAN;
GO

USE LIBMAN;
CREATE TABLE ADMINS (
	USERNAME VARCHAR(64) PRIMARY KEY,
	PASSWD VARCHAR(255),
	"NAME" VARCHAR(64)
);
CREATE TABLE READERS (
	USERNAME VARCHAR(64) PRIMARY KEY,
	PASSWD VARCHAR(255),
	"NAME" VARCHAR(64),
	CNT INTEGER
);
CREATE TABLE BOOKS (
	ID VARCHAR(36) PRIMARY KEY,
	"NAME" VARCHAR(255),
	AUTHOR VARCHAR(255),
	PRICE INTEGER,
	CNT INTEGER
);
CREATE TABLE RECORDS (
	USERNAME VARCHAR(64),
	ID VARCHAR(36),
	BORROWED DATETIME,
	"RETURN" DATETIME,
	PRIMARY KEY (USERNAME,ID),
	FOREIGN KEY (USERNAME) REFERENCES READERS,
	FOREIGN KEY (ID) REFERENCES BOOKS
);